<?php

$slimconfig = array(
	'db' => array(
		'driver' => "mysql",
		'host' => "localhost",
		'username' => "10884fde793b",
		'password' => "kndsu893nksh238723hiusj",
		'database' => "builder",
		'charset' => "utf8",
	),
	'twig' => array(
		'templatepath' => "../templates",
		# This can either be false for "don't cache"
		# or it can be a folder path to a caching dir...
		'cache' => false,
	),
	'displayErrorDetails' => true,
	'addContentLengthHeader' => false,
);

?>
